services:
  ollama:
    image: mockserver/mockserver:latest
    container_name: ollama-mock
    ports:
      - 11434:11434
    environment:
      MOCKSERVER_SERVER_PORT: 11434
    networks:
      - ollama_network