services:
  ollama:
    image: mockserver/mockserver:latest
    container_name: ollama-mock
    ports:
      - 11434:11434
    volumes:
      - ./tests/mocks/initializer.json:/config/initializer.json
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializer.json
      MOCKSERVER_SERVER_PORT: 11434
    networks:
      - ollama_network